#!/bin/bash
#
# chkconfig: 35 90 12
# description: RPi update manager
#

# Get function from functions library
. /etc/init.d/functions

# Start the service FOO
start() {
        echo -n "Starting update manager: "
        /usr/bin/my-os-update.sh &
        ### Create the lock file ###
        touch /var/lock/subsys/my-os-update
        success $"Update manager started"
        echo
}

# Restart the service FOO
stop() {
        echo -n "Stopping update manager server: "
        killproc my-os-update
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/my-os-update
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status my-os-update
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0