#!/bin/bash
#
# chkconfig: 35 90 12
# description: Bluetooth start
#

# Get function from functions library
. /etc/init.d/functions

start() {
        echo -n "Enabling bluetooth"
        /usr/bin/bt-start &
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  *)
        echo $"Usage: $0 {start}"
        exit 1
esac

exit 0