#!/bin/bash

# Commands
HCIATTACH=/usr/bin/hciattach
HCICONFIG=/usr/bin/hciconfig

while true
do

	sleep 5

	${HCIATTACH} /dev/ttyAMA0 bcm43xx 921600 noflow - >/dev/null 2>&1
	if [ $? -eq 0 ]; then
		break
	fi

done

${HCICONFIG} hci0 up
